{% set name = "equalityml" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/equalityml-{{ version }}.tar.gz
  sha256: 4b94aaa4f5273a440eac073280e5f278d21d308a7211beec2bff94460553fd3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - poetry-core
    - pip
  run:
    - python >=3.8.0
    - aif360 >=0.6.0
    - blackboxauditing >=0.1.54
    - dalex >=1.5.0
    - fairlearn >=0.7.0
    - pandas >=1.2.5
    - scikit-learn >=1.0.0
    - numpy >=1.20.3
    - matplotlib-base >=3.6.2
    - scipy >=1.9.3
    - tqdm >=4.64.1

test:
  imports:
    - equalityml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://equalityai.com
  summary: Algorithms for evaluating fairness metrics and mitigating unfairness in supervised machine learning
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dillonroach
